Algoritmo "teste_enquanto"
// Disciplina   : [Linguagem e Lógica de Programação]
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/02/2021
Var
 x, soma : inteiro


Inicio

  escreva ("Digite o primeiro numero: ")
  leia (x)
  
  soma <- 0
  enquanto x <> 0 faca
     soma <- soma + x
     escreva ("Digite outro numero: ")
     leia (x)
  fimenquanto
  
  escreval ("SOMA = ",soma)

Fimalgoritmo