Algoritmo "tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/02/2021
Var
    n, i, resultado  : inteiro


Inicio

    escreva ("Deseja a tabuada para qual valor? ")
    leia (n)
 
    
    para i de 1 ate 10 faca
       resultado <- i * n
       escreval (n," x ", i, " = ", resultado)

    fimpara


Fimalgoritmo